version: 2

defaults: &defaults
  machine:
    image: circleci/classic:201710-02
    docker_layer_caching: true
  steps:
    - checkout
    - run: .circleci/build.sh
    - run: .circleci/test.sh

jobs:
  node 8.9.1:
    <<: *defaults
    environment:
      - NODE_VERSION: 8.9.1
      - DBUS_SESSION_BUS_ADDRESS: /dev/null

  node 9.2.0:
    <<: *defaults
    environment:
      - NODE_VERSION: 9.2.0
      - DBUS_SESSION_BUS_ADDRESS: /dev/null

workflows:
  version: 2

  test_all:
    jobs:
      - node 8.9.1
      - node 9.2.0
